Duplicate page titles
FoodStandardsAgency/register-a-food-business-front-end pull request #304
Opened 2021-01-18 14:20 UTC by david-kasali

2021-01-27 16:28 UTC, jj-perry requested changes

2021-01-27 16:28 UTC, jj-perry commented on public/static/locales/en/common.json
> +  "Contact Details": "Contact details",
Why are these two changed to lower case for the second word and not the rest? Shouldn't the key also match the value?

2021-01-27 16:28 UTC, jj-perry commented on pages_unit_tests/operator-address.test.js
>        const header = wrapper.find(Heading);
Needs to test the alternative of the conditional as well, when role isn't partnership
Need to add similar tests to address-select and address-manual to test conditional headings.

2021-01-27 16:28 UTC, jj-perry commented on pages/contact-representative.js
> +        {props.t("Contact Details")}
Would suggest changing this to 'Contact representative details' as users could assume it means establishment details and enter the wrong information.

2021-03-15 15:04 UTC, paul-burnett approved these changes

2021-03-15 15:09 UTC, merged