added laguidancelink
FoodStandardsAgency/register-a-food-business-front-end pull request #432
Opened 2023-05-11 08:22 UTC by Joe-Cun-Civica

added laguidance link and test

2023-05-15 17:47 UTC, ernestas-leliuga commented
> ## Unit Test Results
>     1 files  ±0    81 suites  ±0   2m 26s [⏱️](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.7.0/README.md#the-symbols) -30s 790 tests +1  773 [✔️](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.7.0/README.md#the-symbols)  - 16  0 [💤](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.7.0/README.md#the-symbols) ±0  17 [❌](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.7.0/README.md#the-symbols) +17  806 runs  +1  789 [✔️](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.7.0/README.md#the-symbols)  - 16  0 [💤](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.7.0/README.md#the-symbols) ±0  17 [❌](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.7.0/README.md#the-symbols) +17 
> 
> For more details on these failures, see [this check](https://github.com/FoodStandardsAgency/register-a-food-business-front-end/runs/13396743814).
> 
> Results for commit [fc90d35](https://github.com/FoodStandardsAgency/register-a-food-business-front-end/commit/fc90d35c2cfba836a9330c506d950979a71f0c5c). ± Comparison against base commit [a25ee6d](https://github.com/FoodStandardsAgency/register-a-food-business-front-end/commit/a25ee6df00a22c8bd1e001327ac23a8d54ff9a37).

There are 17 tests that are failing, all of which have the same error:

>  Template render error: (/home/runner/work/register-a-food-business-front-end/register-a-food-business-front-end/pages/summary-confirmation.njk) [Line 81, Column 12]
> 
>       unknown block tag: else

2023-05-15 20:40 UTC, ernestas-leliuga requested changes
There are several issues that need to be addressed before merging

2023-06-20 12:07 UTC, ernestas-leliuga approved these changes

2023-06-23 10:44 UTC, simon-says-test approved these changes

2023-06-26 13:56 UTC, merged